### PR TITLE
fix: LogProvider as option injected to unleash.

### LINKED ISSUE #430: Providing custom LoggerProvider as an option.
Today one have to register a custom `LoggerProvider` before requiring unleash. This feels like a hack. 

Unleash should accept a custom log-provider as an option to the start command like this:

```javascript
const unleash = require('unleash-server');

unleash
  .start({
    databaseUrl: 'postgres://unleash_user:passord@localhost:5432/unleash',
    port: 4242,
    getLogger: <aCustomLoggerProvider>
  })
```

### PR DESCRIPTION
**Pull request by ivarconr**
Instead of instructing users to do static calls in to Unleash, she should instead be allowed to specify the log provider as an option to Unleash.

This commit introduces the "getLogger" option, a function responsible for creating a logger.

```javascript
const unleash = require('unleash-server');

unleash
  .start({
    databaseUrl: 'postgres://unleash_user:passord@localhost:5432/unleash',
    port: 4242,
    getLogger: <aCustomLoggerProvider>
  })
```

This closes #430

Todo:

- [x] Update getting-started guide

### CODE REVIEW

File: lib/server-impl.js [hunk 1]
```diff
@@ -16,14 +14,14 @@ const AuthenticationRequired = require('./authentication-required');
...
     // Database dependecies (statefull)
+    const logger = options.getLogger('server-impl.js');
     const stores = createStores(options);
     const eventBus = new EventEmitter();
 
     const config = Object.assign(
         {
             stores,
             eventBus,
-            logFactory,
```
Comment (moolen) [inline lib/server-impl.js]: A user could potentially access this property through `stateService.config.logFactory`. I'd suggest moving this specific change to 4.x.

Comment (ivarconr) [reply lib/server-impl.js]: Thanks, you are absolutely right!
