### PR TITLE
fix: fix project settings path for oss

### LINKED ISSUE #8618: Active tab not working properly in Project settings of OSS
### Describe the bug

When you select API Access and Default Strategy in the Project settings of OSS, the Active Tab moves to Flags.

### Steps to reproduce the bug

1. Go to Project Settings
2. Click API access or Default Strategy menu

### Expected behavior

Active tab should be Settings.

### Logs, error output, etc.

_No response_

### Screenshots

https://github.com/user-attachments/assets/22b8ffb7-b755-4d56-a8a5-b7a412299bde

### Additional context

_No response_

### Unleash version

6.3.0

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

_No response_

### PR DESCRIPTION
**Pull request by sjaanus**
**Issue fix:** Resolves #8618, where environments were incorrectly appended to the route.
**Change:** Introduces `ossPath` specifically for OSS users, as OSS lacks the default `/settings` path, starting instead from `api-access`.

### CODE REVIEW

File: frontend/src/component/project/Project/Project.tsx [hunk 1]
```diff
@@ -180,7 +180,7 @@ export const Project = () => {
         },
         {
             title: 'Project settings',
-            path: `${basePath}/settings${isOss() ? '/environments' : ''}`,
+            path: `${basePath}/settings`,
```
Comment (sjaanus) [inline frontend/src/component/project/Project/Project.tsx:183]: This was causing the issue in https://github.com/Unleash/unleash/issues/8618, appending environments to route, since previously OSS only saw environments.

File: frontend/src/component/project/Project/ProjectSettings/Settings/Settings.tsx [hunk 2]
```diff
@@ -21,17 +20,6 @@ export const Settings = () => {
     const { isOss } = useUiConfig();
     usePageTitle(`Project configuration – ${projectName}`);
 
-    if (isOss()) {
```
Comment (sjaanus) [inline frontend/src/component/project/Project/ProjectSettings/Settings/Settings.tsx:24]: Removeing, because not true anymore.

File: frontend/src/component/project/Project/Project.tsx [hunk 3]
```diff
@@ -180,7 +181,8 @@ export const Project = () => {
...
+            ossPath: `${basePath}/settings/api-access`,
```
Comment (sjaanus) [inline frontend/src/component/project/Project/Project.tsx:185]: Introducing ossPath, because oss does not have default /settings path, but they start from api-access.

**Review by thomasheartman — APPROVED** [review]

**Review by FredrikOseberg — APPROVED** [review]
LGTM
