### PR TITLE
fix(migration): Unleash should not start if migration fails.

### LINKED ISSUE #320: Unleash should not start if migration fails
Stop catching on [server-impl.js#L42](https://github.com/Unleash/unleash/blob/master/lib/server-impl.js#L42)

### PR DESCRIPTION
**Pull request by ivarconr**
Closes #320

### CODE REVIEW

File: lib/server-impl.js [hunk 1]
```diff
@@ -38,12 +38,17 @@ function createApp(options) {
...
-        .catch(err => logger.error('failed to migrate db', err))
-        .then(() => createApp(options));
+    try {
+        await migrator({ databaseUrl: options.databaseUrl });
+    } catch (err) {
+        logger.error('Failed to migrate db', err);
+        throw err;
+    }
+
+    return await createApp(options);
```
Comment (SimenB) [inline lib/server-impl.js]: No need for the `await` here
