### PR TITLE
fix: enforce weight precision to 1 decimal

### LINKED ISSUE #2222: bug: Variants "Fix Setting" has Incorrect Behavior
### Describe the bug

Using the "fix" percentage on variants causes issues. Setting to 33.33% can cause an error (event logs show the weight being set as 333.29999999999995 while the other (variable set) percentage is set to 667.
This can also be seen by using any more than 1 decimal point. Using two or more causes the weights to add up over 1000. This causes the UI to show a percentage, but the actual weight is different. Ex. setting a variant to 55.555% causes one weight to be 505.55 and the other to be 495. This means the total is 1000.55, meaning 495/1000.55 is actually 49.47%. Not a huge issue but it is incorrect. 
Screenshot 2022-10-20 at 15 29 41
Screenshot 2022-10-20 at 15 26 22

### Steps to reproduce the bug

1. Create a feature toggle
2. add at least two variants
3. set one variant percentage manually with more than 1 decimal point
4. check event logs for actual weights set in the system 

### Expected behavior

I would expect weights to accurately add up to 1000 and to be accurate in the UI so users can correctly set up experiments. 

### Logs, error output, etc.

_No response_

### Screenshots

Screenshot 2022-10-20 at 15 29 41
Screenshot 2022-10-20 at 15 26 22

### Additional context

_No response_

### Unleash version

4.16.1

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

_No response_

### PR DESCRIPTION
**Pull request by gastonfournier**
## About the changes
According to our docs, we only support up to 1 decimal place for weights. This is to use integers to represent the percentages (we divide them by 10) and supporting more decimals results in bad maths due to floating point arithmetics. 

This PRs adds Frontend and Backend validations to enforce this restriction

Closes #2222

## Discussion points
Should we reconsider supporting more decimal places, that door remains open, but for now we'll just adhere to our documentation because that change would require some development.

### CODE REVIEW

File: src/lib/schema/feature-schema.ts [hunk 1]
```diff
@@ -50,7 +50,13 @@ export const variantValueSchema = joi
 
 export const variantsSchema = joi.object().keys({
     name: nameType,
-    weight: joi.number().min(0).max(1000).required(),
+    weight: joi
+        .number()
+        .integer()
+        .message('Weight only supports 1 decimal')
```
Comment (gastonfournier) [inline src/lib/schema/feature-schema.ts:56]: This is just to improve the error message. Otherwise it'll show that the value has to be integer which is misleading for oru users

File: src/lib/schema/feature-schema.test.ts [hunk 2]
```diff
@@ -70,6 +70,56 @@ test('should allow weightType=fix', () => {
...
+                name: 'variant-a',
+                weight: 1.5,
+                weightType: 'fix',
+                stickiness: 'default',
+            },
+        ],
+    };
+
+    const { error } = featureSchema.validate(toggle);
+    expect(error.details[0].message).toEqual('Weight only supports 1 decimal');
```
Comment (chriswk) [inline src/lib/schema/feature-schema.test.ts:94]: Why should this fail? There's only 1 decimal in the actual variant?

Comment (gastonfournier) [reply src/lib/schema/feature-schema.test.ts:94]: The problem is that our weight range goes from 0 to 1000, where 1000 represents 100% and 1.5 represents 0.15%. This way of representing values as integers is common in representing money, but it is a bit confusing IMO, especially when you see things like this: 
1. I send 1 to the API (or 1.5 to the API)
2. I get 0.1% as result (I get only 1 decimal is supported when I sent only 1 decimal)

It has the overhead of having to know that the API payload is being interpreted differently

**Review by nunogois — APPROVED** [review]
LGTM 👍

File: src/lib/schema/feature-schema.test.ts (hunk 2 above)
Comment (gastonfournier) [reply src/lib/schema/feature-schema.test.ts:94]: Exactly, the error message is confusing but I wanted to test the two error messages (the old one in the text below and the new one in this test). The test description seems right IMO: `should not allow weightType=fix with floats` which is exactly what we want, but the message we're validating is a bit misleading from a backend perspective. If we could just validate against some error type (e.g. `INVALID_TYPE`) that'd be easier.
